name = "contador-dorado"
main = "worker.js"
compatibility_date = "2023-12-01"

[[durable_objects.bindings]]
name = "CONTADOR_STATS"
class_name = "ContadorStats"

[[migrations]]
tag = "v2"
new_classes = ["ContadorStats"]
